### ISSUE TITLE
Unprocessable Entity - The following fields of the billingAddress are missing: postalCode, city

### ISSUE THREAD

**Issue by royberris** [vendrhub/vendr-payment-provider-mollie#4]
Hello,

When trying to use this payment provider I get the following error:

```
Unprocessable Entity - The following fields of the billingAddress are missing: postalCode, city
```

I did set the aliases in the payment provider configuration. Any idea on what is missing, and how I can fix this?

**Comment by mattbrailsford** [comment]
What version of Vendr / the Mollie provider are you using?

**Comment by royberris** [comment]
Vendr 2.0.2 and Mollie 2.0.0

**Comment by mattbrailsford** [comment]
And you definitely have the relevant properties in your orders properties collection?

I can't see anything wrong the code here that copies them over 🤔

https://github.com/vendrhub/vendr-payment-provider-mollie/blob/v2/dev/src/Vendr.PaymentProviders.Mollie/MollieOneTimePaymentProvider.cs#L121-L128

**Comment by royberris** [comment]
Let me share some more info. We've just upgraded from Vendr 1.8.6 to Vendr 2.0.2. I did a full reinstall, so first removing everything (except for the database). I also removed the files from the `App_Plugins` folder. Then I did a reinstall with the new version. 
We're using Vendr.Checkout and only have the payment provider for Mollie installed.

Configuration screen:

![image](https://user-images.githubusercontent.com/25608596/138822718-32ec48cf-aacf-4d5b-a210-07f828fa0873.png)

Then I fill in my order with these details:

![image](https://user-images.githubusercontent.com/25608596/138822938-adb574a2-6a7e-4c0b-b415-455163a14dc3.png)

And choose Mollie:

![image](https://user-images.githubusercontent.com/25608596/138823032-e2083d0f-3579-42c3-97d4-e5d01e2581f2.png)

And results in this

```
[MollieApiException: Unprocessable Entity - The following fields of the billingAddress are missing: postalCode, city]
   Vendr.Extensions.HtmlHelperExtensions.RenderPaymentForm(HtmlHelper htmlHelper, OrderReadOnly order, IDictionary`2 htmlAttributes, IOrderService orderService, IPaymentMethodService paymentMethodService, IPaymentProviderService paymentProviderService, PaymentProviderContextFactory paymentProviderContextFactory, IOrderNumberGenerator orderNumberGenerator, IUnitOfWorkProvider uowProvider, IMembershipHelper membershipHelper) +4106
   Vendr.Extensions.HtmlHelperExtensions.BeginPaymentForm(HtmlHelper htmlHelper, OrderReadOnly order, IDictionary`2 htmlAttributes) +213
   ASP._Page_App_Plugins_VendrCheckout_views_VendrCheckoutReviewPage_cshtml.Execute() in C:\Projects\KWBN\KWBN\Kwbn.Website\App_Plugins\VendrCheckout\views\VendrCheckoutReviewPage.cshtml:11
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +252
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +148
   System.Web.WebPages.StartPage.ExecutePageHierarchy() +86
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +107
   Umbraco.Web.Mvc.ProfilingView.Render(ViewContext viewContext, TextWriter writer) in C:\Git werk\Umbraco sources\Umbraco-CMS\src\Umbraco.Web\Mvc\ProfilingView.cs:25
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +378
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +91
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +795
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +795
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +795
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +795
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +81
   System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult) +188
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +52
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +39
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState) +43
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +651
   System.Web.<>c__DisplayClass285_0.<ExecuteStepImpl>b__0() +40
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +155
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +134
```

**Comment by mattbrailsford** [comment]
Hmmm, then I really can't see why this is wrong. Best I could suggest is to pull the source code down locally and compile your own build to debug into the `GenerateForm` method and see if the address is indeed being populated and if not, see if the settings are actually getting pulled through and that you have properties on the order with those configured keys.

**Comment by royberris** [comment]
For anyone in the future.

Aliasses for `Vendr.Checkout`

StreetAndNumber is `billingAddressLine1`.
City is `billingCity`.
Zipcode is `billingZipCode`.

**Comment by royberris** [comment]
Works now! Thanks for developing this payment provider.

**Comment by mattbrailsford** [comment]
Ahhh, fantastic. Good spot and glad you got it working.

Just a note (I need to add it to the docs) but when using the Mollie payment provider, you need to make sure you set your store configuration "Order Rounding" to "line" rather than the default "unit".

**Comment by royberris** [comment]
@mattbrailsford thanks didn't know that. One more question, off topic. 

I set my (local) environment to test. Does that mean that the order isn't processed? I get the success screen from Vendr, but when checking the orders section I don't see my order. I suppose this is because of the test mode?

**Comment by mattbrailsford** [comment]
@royberris it'll more than likely be the webhooks. Checkout the docs here for how to test the webhook locally https://vendr.net/docs/payment-providers/mollie/2.0.0/mollie-onetime/how-to-guides/testing-mollie-webhooks-locally/
